# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: ajliepman.pw
title: Alexander J. Liepman
email: alexanderliepman@gmail.com
author: Alexander J. Liepman
description: Alexander Liepman is an Internet Entrepreneur Based in Omaha Nebraska.
copyright: 'Copyright &copy; 2016 Alexander J. Liepman. All Rights Reserved.'
credits: ''

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/ajliepman
  - title: instagram
    url: https://instagram.com/a.jl
  - title: linkedin
    url: https://linkedin.com/in/ajliepman
